-- MySQL Script generated by MySQL Workbench
-- sam. 09 déc. 2017 17:36:47 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 4LDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `4LDB` ;

-- -----------------------------------------------------
-- Schema 4LDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `4LDB` DEFAULT CHARACTER SET utf8 ;
USE `4LDB` ;

-- -----------------------------------------------------
-- Table `4LDB`.`etape`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4LDB`.`etape` ;

CREATE TABLE IF NOT EXISTS `4LDB`.`etape` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `arrivee` VARCHAR(45) NULL,
  `depart` VARCHAR(45) NULL,
  `time` TIMESTAMP(0) NULL DEFAULT NOW(),
  `time_arrivee` TIMESTAMP(0) NULL,
  `time_depart` TIMESTAMP(0) NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `arrivee_UNIQUE` (`arrivee` ASC),
  UNIQUE INDEX `depart_UNIQUE` (`depart` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4LDB`.`pointgps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4LDB`.`pointgps` ;

CREATE TABLE IF NOT EXISTS `4LDB`.`pointgps` (
  `lattitude` FLOAT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `longitude` FLOAT NULL,
  `vitesse` FLOAT NULL,
  `roll` FLOAT NULL,
  `magx` FLOAT NULL,
  `altitude` FLOAT NULL,
  `etape_id` INT NOT NULL,
  `time` TIMESTAMP(0) NULL DEFAULT NOW(),
  `pitch` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pointgps_etape1_idx` (`etape_id` ASC),
  CONSTRAINT `fk_pointgps_etape1`
    FOREIGN KEY (`etape_id`)
    REFERENCES `4LDB`.`etape` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4LDB`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4LDB`.`image` ;

CREATE TABLE IF NOT EXISTS `4LDB`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` TIMESTAMP(0) NULL DEFAULT NOW(),
  `etape_id` INT NOT NULL,
  `pointgps_id` INT NOT NULL,
  `path` VARCHAR(100) NOT NULL,
  `uploaded` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `date_UNIQUE` (`time` ASC),
  INDEX `fk_image_etape1_idx` (`etape_id` ASC),
  INDEX `fk_image_pointgps1_idx` (`pointgps_id` ASC),
  CONSTRAINT `fk_image_etape1`
    FOREIGN KEY (`etape_id`)
    REFERENCES `4LDB`.`etape` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_image_pointgps1`
    FOREIGN KEY (`pointgps_id`)
    REFERENCES `4LDB`.`pointgps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4LDB`.`messageAWS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4LDB`.`messageAWS` ;

CREATE TABLE IF NOT EXISTS `4LDB`.`messageAWS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `corpus` VARCHAR(156) NULL,
  `pseudo` VARCHAR(156) NULL,
  `time` TIMESTAMP(0) NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4LDB`.`message4L`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4LDB`.`message4L` ;

CREATE TABLE IF NOT EXISTS `4LDB`.`message4L` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `corpus` VARCHAR(45) NULL,
  `time` TIMESTAMP(0) NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
